#!/usr/bin/env bash
#
# Author: Alalilacias
# Description: Creates custom functions in .zshrc when invoked.
# Syntax: source pfunctions
# Version: 0.2

# Makes all cd calls use the ll alias to lists files below the directory we moved to the way I like it.
cdl() {
  cd "$@" && ll
}

# Allows to create a directory and change to it. Have never used it.
mkcd() {
  mkdir -p "$1" && cd "$1"
}

# Measure the startup time of the shell (default: $SHELL) by running it 10 times.
# Uses '/usr/bin/time' to track execution time.
# The shell starts in interactive mode (-i) but only executes 'exit' (-c exit).
timezsh() {
  local shell=${1:-$SHELL}                    # Use the provided shell or default to $SHELL
  repeat 10 /usr/bin/time "$shell" -i -c exit # Run the timing test 10 times
}

# Helps more easily compile cpp files
compile_cpp() {
  local base_args=(
    -std=c++17                                            # Language Standard
    -pedantic-errors                                      # Disabling compiler extensions
    -Wall -Weffc++ -Wextra -Wconversion -Wsign-conversion # Increase warning level
    -Werror                                               # Treat warnings as errors
    -O2                                                   # Optimize for release (Change to -O for debug and -O3 for aggressive optimization)
  )
  local output_file="$1"
  local source_file="$2"

  if [[ -z "$output_file" || -z "$source_file" ]]; then
    echo "Usage: compile_cpp <output_file> <source_file>"
    return 1
  fi

  g++ "${base_args[@]}" -o "$output_file" "$source_file"
}
