#!/usr/bin/env bash
# Author: Alalilacias
# Description: Sources all necessary functions for the .zshrc
# Syntax: source "$HOME/.dotfiles/.config/zsh/sources"
# Version: 0.8

###########
# Imported
###########

if [ -d "$HOME/.dotfiles/submodules/fast-syntax-highlighting" ]; then
  source "$HOME/.dotfiles/submodules/fast-syntax-highlighting/fast-syntax-highlighting.plugin.zsh"
fi

if [ -d "$HOME/.dotfiles/submodules/zsh-autocomplete" ]; then
  source "$HOME/.dotfiles/submodules/zsh-autocomplete/zsh-autocomplete.plugin.zsh"
fi

###########
# Personal
###########

if [ -f "$HOME/.dotfiles/.config/zsh/aliases" ]; then
  source "$HOME/.dotfiles/.config/zsh/aliases"
fi

if [ -f "$HOME/.dotfiles/.config/zsh/pfunctions" ]; then
  source "$HOME/.dotfiles/.config/zsh/pfunctions"
fi

###########
# Toolchains
###########

# Dotfiles bin
if [ -d "$HOME/.dotfiles/bin" ]; then
  export PATH="$HOME/.dotfiles/bin:$PATH"
fi

# Rust (cargo)
if [ -d "$HOME/.dotfiles/.local/tools/rust/.cargo/bin" ]; then
  export CARGO_HOME="$HOME/.dotfiles/.local/tools/rust/.cargo"
  export RUSTUP_HOME="$HOME/.dotfiles/.local/tools/rust"
  export PATH="$CARGO_HOME/bin:$PATH"
fi

# Go
if [ -d "$HOME/.dotfiles/.local/tools/go/bin" ]; then
  export GOROOT="$HOME/.dotfiles/.local/tools/go"
  export GOPATH="$HOME/go"
  export GOBIN="$GOPATH/bin"
  export PATH="$GOROOT/bin:$GOBIN:$PATH"
fi

# Dotnet
if [ -d "$HOME/.dotfiles/.local/tools/dotnet" ]; then
  export DOTNET_ROOT="$HOME/.dotfiles/.local/tools/dotnet"
  export PATH="$DOTNET_ROOT:$PATH"
fi

# Ruby (gems)
if [ -d "$HOME/.dotfiles/.local/tools/gems/bin" ]; then
  export GEM_HOME="$HOME/.dotfiles/.local/tools/gems"
  export PATH="$GEM_HOME/bin:$PATH"
fi
