#!/usr/bin/env bash
# Author: Alalilacias
# Description: Sources all necessary functions for the .zshrc
# Syntax: source "$HOME/.dotfiles/.config/zsh/sources"
# Version: 0.8

# Core
# See these two scripts for the functions used in this script.
source "$HOME/.dotfiles/.config/zsh/modules/aliases/core_aliases"
source "$HOME/.dotfiles/.config/zsh/modules/functions/core_functions"

simple-file-source "$HOME/.dotfiles/.config/zsh/modules/aliases/aliases"
simple-file-source "$HOME/.dotfiles/.config/zsh/modules/functions/functions"

simple-file-source "$HOME/.dotfiles/.config/zsh/modules/prompt/prompt.zsh"
simple-file-source "$HOME/.dotfiles/.config/zsh/modules/options/options.zsh"

# Plugins

file-if-directory-source "$HOME/.dotfiles/submodules/fast-syntax-highlighting" "fast-syntax-highlighting.plugin.zsh"
file-if-directory-source "$HOME/.dotfiles/submodules/zsh-autocomplete/" "zsh-autocomplete.plugin.zsh"

# Toolchains

for file in $HOME/.dotfiles/.config/zsh/modules/{toolchains,prompt,options}/*.zsh; do
  simple-file-source "$file"
done
