#!/usr/bin/env bash
# Author: Alalilacias
# Description: Sources all necessary functions for the .zshrc
# Syntax: source "$HOME/.dotfiles/.config/zsh/sources"
# Version: 0.5

###########
# Imported
###########

# Enable fast syntax highlighting
if [ -d "$HOME/.dotfiles/submodules/fast-syntax-highlighting" ]; then
  source "$HOME/.dotfiles/submodules/fast-syntax-highlighting/fast-syntax-highlighting.plugin.zsh"
fi

# Enable zsh-autocomplete
if [ -d "$HOME/.dotfiles/submodules/zsh-autocomplete" ]; then
  source "$HOME/.dotfiles/submodules/zsh-autocomplete/zsh-autocomplete.plugin.zsh"
fi

###########
# Personal
###########

# Set up aliases
if [ -f "$HOME/.dotfiles/.config/zsh/aliases" ]; then
  source "$HOME/.dotfiles/.config/zsh/aliases"
fi

# Set up personal functions
if [ -f "$HOME/.dotfiles/.config/zsh/pfunctions" ]; then
  source "$HOME/.dotfiles/.config/zsh/pfunctions"
fi
