#!/usr/bin/env bash
#
# Author: Alalilacias
# Description: Installs dotfiles into system not configured by them.
# Syntax: ./install
# Version: 0.1

# TODO Finish setting up the script. That includes:
# - Modify install.json or the method for configuration of installation database used by script.
# - Finish setting up installation.

# Global Variables
# Directories
DOTFILES_DIR="${HOME}/.dotfiles/"
DOTCONFIG_DIR="${DOTFILES_DIR}.config/dotfiles/"
# Function files
SETUP_FUNCS="${DOTCONFIG_DIR}/dotfiles-setup"
INSTALL_FUNCS="${DOTCONFIG_DIR}/dotfiles-installation"
#Utility
PACKAGE_MANAGER=""

main() {
  manage_setup "$@"
  manage_installation
}

# Help function, invoke on mistakes and whenever the user asks for it.
usage() {
  cat <<-EOF
Usage $0 [options]

$0 is a script that installs the appropiate mix of programs into the current system.
It is meant to be used at the root of the dotfiles folder and it uses mainly the package manager
of the system to install the programs. Some programs can be installed without it, but they're the exception.

Current available options are:
-d| --devenv    Specify the development environment to install. 
                Remember to include at least a single environment.
                More than one works provided they're separated by commas not spaces (e.g. java,cpp,server).
                Lack of specification will install all environments.
-f| --force     Force installation, overwriting existing files
-h| --help      Show this help message
-l| --log-level The log level to use. 
                See .config/dotfiles/utils/bash_logging/bash_logging.md for available levels.
                Default is INFO. Recommended are DEBUG, INFO or ERROR.
EOF
}
manage_setup() {
  # Sourcing the file where most of the setup functions are.
  # Keep in mind that this file sources the following relevant:
  # - Variables: CLEANED_ARGS, DEVENVS, FORCE, LOG_LEVEL
  # - Functions: start_logger, extract_log_level, readopts, extract_pm
  source "${SETUP_FUNCS}"

  # Extract log level and cleaned arguments and initialize the logger.
  extract_log_level "$@"
  start_logger
  log_debug "Starting installation script with the following cleaned arguments: ${CLEANED_ARGS[*]}"

  readopts "${CLEANED_ARGS[@]}"
  log_debug "Parsed options: FORCE=$FORCE, DEVENVS=${DEVENVS[*]}"

  check_dev_present "${CLEANED_ARGS[@]}"

  PACKAGE_MANAGER=$(extract_pm)
  log_debug "Detected package manager: $PACKAGE_MANAGER"
}
manage_installation() {
  # Setup finished, starting installation.
  # Sourcing the file where the installation functions are.
  # Keep in mind that this file sources the following relevant:
  # - Variables:
  # - Functions: check_databaseparser_availability
  source "${INSTALL_FUNCS}"

  check_databaseparser_availability

  install_all_environments
}

main "$@"
