#!/usr/bin/env bash
#
# Author: Alalilacias
# Description: Helper script to create all connections necessary for the system to use the configurations set in this directory
# Syntax: (. ./"$HOME/.dotfiles/.config/dotfiles/connections")
# Version: 0.4

# Dotfiles path (configurable via environment variable)
DOTFILES_DIR="${DOTFILES_DIR:-$HOME/.dotfiles}"
# Subdirectory paths
DOTFILES_BIN="$DOTFILES_DIR/bin"
DOTFILES_CONFIG="$DOTFILES_DIR/.config"
DOTFILES_SUBMODULES="$DOTFILES_DIR/submodules"

# Functions
make_executable() {
  local file="$1"
  if [[ ! -f "$file" ]]; then
    echo "$file does not exist. Skipping."
  elif [[ ! -x "$file" ]]; then
    echo "$file is not executable. Making it executable..."
    chmod +x "$file" && echo "$file has been made executable!" || echo "Failed to make $file executable."
  else
    echo "$file is already executable."
  fi
}
create_symlink() {
  local source="$1"
  local target="$2"
  if [[ ! -L "$target" && ! -e "$target" ]]; then
    echo "Creating symlink for $source..."
    ln -sf "$source" "$target" && echo "Symlink created for $source." || echo "Failed to create symlink for $source."
  else
    echo "Symlink for $source already exists."
  fi
}
