#!/usr/bin/env bash
# Author: Alalilacias
# Description: Installs essential files for the correct working of the dotfile configuration
# Syntax: (. ./"$HOME/.dotfiles/.config/dotfiles/essential-installs")
# Version: 0.1

# Constants
HOME_DIR="$HOME"
JSON_FILE="$HOME_DIR/.dotfiles/.config/dotfiles/config/install.json"

# Main
source "$HOME_DIR/.dotfiles/.config/dotfiles/inst-funcs"

executable="jq"
if ! is_app_executable "$executable"; then
  source "$HOME/.dotfiles/.config/dotfiles/scripts/jq"
fi

essential_packs=$(jq -r '.essential_packs[] | .package' "$JSON_FILE")

for package in $essential_packs; do
  executable=$(jq -r ".essential_packs[] | select(.package == \"$package\") | .executable" "$JSON_FILE")
  if ! is_app_executable "$executable"; then
    source_file=$(jq -r ".essential_packs[] | select(.package == \"$package\") | .source_file" "$JSON_FILE")
    install_package "$package" "$source_file"
  else
    echo "$package is already installed"
  fi
done
