#!/usr/bin/env bash
# Author: Alalilacias
# Description: Installs optional files for the correct working of the dotfile configuration
# Syntax: (. ./"$HOME/.dotfiles/.config/dotfiles/optional-installs")
# Version: 0.3

# Constants
HOME_DIR="$HOME"
JSON_FILE="$HOME_DIR/.dotfiles/.config/dotfiles/config/install.json"
export PATH="$HOME_DIR/.dotfiles/bin:$PATH"

# Main
command -v jq &>/dev/null || source "$HOME/.dotfiles/.config/dotfiles/scripts/jq"
source "$HOME_DIR/.dotfiles/.config/dotfiles/inst-funcs"

jq -c '.optional_packs[]' "$JSON_FILE" | while read -r pack; do
  pkg=$(jq -r '.package' <<<"$pack")
  exe=$(jq -r '.executable' <<<"$pack")
  src=$(jq -r '.source_file' <<<"$pack" | sed "s|{HOME_DIR}|$HOME|g")

  if ! is_app_executable "$exe"; then
    install_package "$pkg" "$src"
  else
    echo "$pkg is already installed"
  fi
done
