#!/usr/bin/env bash
# Author: Alalilacias
# Description: Installs cmake
# Syntax: source "$HOME/.dotfiles/.config/dotfiles/scripts/cmake"
# Version: 0.1

echo "cmake not found, installing..."
if command -v apt &>/dev/null; then
  
  sudo apt install -y cmake
else
  echo "Package manager not supported"
fi
