#!/usr/bin/env bash
# Author: Alalilacias
# Description: Installs curl
# Syntax: source "$HOME/.dotfiles/.config/dotfiles/scripts/curl"
# Version: 0.1

echo "curl not found, installing..."
if command -v apt &>/dev/null; then
  
  sudo apt install -y curl
else
  echo "Package manager not supported"
fi
