#!/usr/bin/env bash
# Author: Alalilacias
# Description: Installs Fdfind
# Syntax: source "$HOME/.dotfiles/.config/dotfiles/scripts/fd-find"
# Version: 0.1

echo "fd-find not found, installing..."
if command -v apt &>/dev/null; then
  sudo apt update
  sudo apt install -y fd-find
else
  echo "Package manager not supported"
fi
