#!/usr/bin/env bash
# Author: Alalilacias
# Description: Installs fish
# Syntax: source "$HOME/.dotfiles/.config/dotfiles/scripts/fish"
# Version: 0.1

echo "fish not found, installing..."
if command -v apt &>/dev/null; then
  sudo apt update
  sudo apt install -y fish
else
  echo "Package manager not supported"
fi
