#!/usr/bin/env bash
# Author: Alalilacias
# Description: Installs fnm
# Syntax: source "$HOME/.dotfiles/.config/dotfiles/scripts/fnm"
# Version: 0.2

log_info "fnm not found, installing..."

curl -fsSL https://fnm.vercel.app/install | bash -s -- --skip-shell
