#!/usr/bin/env bash
# Author: Alalilacias
# Description: Installs fnm
# Syntax: source "$HOME/.dotfiles/.config/dotfiles/scripts/fnm"
# Version: 0.1

echo "fnm not found, installing..."

curl -fsSL https://fnm.vercel.app/install | bash
