#!/usr/bin/env bash
# Author: Alalilacias
# Description: Installs Fzf
# Syntax: source "$HOME/.dotfiles/.config/dotfiles/scripts/fzf"
# Version: 0.1

echo "fzf not found, installing..."
if command -v apt &>/dev/null; then
  
  sudo apt install -y fzf
else
  echo "Package manager not supported"
fi
