#!/usr/bin/env bash
# Author: Alalilacias
# Description: Install github-cli. Provided directly in their repository.
# Version: 0.0.1

(type -p wget >/dev/null || (sudo apt update && sudo apt install wget -y)) &&
  sudo mkdir -p -m 755 /etc/apt/keyrings &&
  out=$(mktemp) && wget -nv -O$out https://cli.github.com/packages/githubcli-archive-keyring.gpg &&
  cat $out | sudo tee /etc/apt/keyrings/githubcli-archive-keyring.gpg >/dev/null &&
  sudo chmod go+r /etc/apt/keyrings/githubcli-archive-keyring.gpg &&
  sudo mkdir -p -m 755 /etc/apt/sources.list.d &&
  echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list >/dev/null &&
  sudo apt update &&
  sudo apt install gh -y

read -r -p "Do you want to log into GitHub now with 'gh auth login'? [y/N] " ans
ans="${ans,,}" # convert to lowercase

if [[ "$ans" == "y" || "$ans" == "yes" ]]; then
  gh auth login
else
  echo "Skipping GitHub login. You can run 'gh auth login' later."
fi

read -r -p "Do you want to log into GitHub now with 'gh auth login'? [y/N] " ans
ans="${ans,,}" # convert to lowercase

if [[ "$ans" == "y" || "$ans" == "yes" ]]; then
  gh auth refresh -h github.com -s delete_repo
else
  echo "Skipping GitHub login. You can run 'gh auth login' later."
fi
