#!/usr/bin/env bash
# Author: Alalilacias
# Description: Installs Git
# Syntax: source "$HOME/.dotfiles/.config/dotfiles/scripts/git"
# Version: 0.1

echo "git not found, installing..."
if command -v apt &>/dev/null; then
  sudo apt update
  sudo apt install -y git
else
  echo "Package manager not supported"
fi
