#!/usr/bin/env bash
# Author: Alalilacias
# Description: Installs httrack
# Syntax: source "$HOME/.dotfiles/.config/dotfiles/scripts/httrack"
# Version: 0.1

echo "httrack not found, installing..."
if command -v apt &>/dev/null; then
  
  sudo apt install -y httrack
else
  echo "Package manager not supported"
fi
