#!/usr/bin/env bash
# Author: Alalilacias
# Description: Installs imagemagick
# Syntax: source "$HOME/.dotfiles/.config/dotfiles/scripts/imagemagick"
# Version: 0.1

echo "imagemagick not found, installing..."
if command -v apt &>/dev/null; then
  sudo apt update
  sudo apt install -y imagemagick
else
  echo "Package manager not supported"
fi
