#!/usr/bin/env bash
# Author: Alalilacias
# Description: Installs JQ
# Syntax: source "$HOME/.dotfiles/.config/dotfiles/scripts/jq"
# Version: 0.1

echo "jq not found, installing..."
if command -v apt &>/dev/null; then
  sudo apt update
  sudo apt install -y jq
else
  echo "Package manager not supported"
fi
