#!/usr/bin/env bash
# Author: Alalilacias
# Description: Installs jq
# Syntax: source "$HOME/.dotfiles/.config/dotfiles/scripts/jq"
# Version: 0.2

log_debug "jq not found, installing..."

if command -v apt &>/dev/null; then
  sudo apt update -qq
  sudo apt install -y jq
  PKG_MANAGER_UPDATED=true
else
  log_error "Package manager not supported"
  return 1
fi

log_debug "jq installation finished."
