#!/usr/bin/env bash
# Author: Alalilacias
# Description: Installs julia
# Syntax: source "$HOME/.dotfiles/.config/dotfiles/scripts/julia"
# Version: 0.1

echo "julia not found, installing..."
if command -v apt &>/dev/null; then
  sudo apt update
  sudo apt install -y julia
else
  echo "Package manager not supported"
fi
