#!/usr/bin/env bash
# Author: Alalilacias
# Description: Installs Kitty
# Syntax: source "$HOME/.dotfiles/.config/dotfiles/scripts/kitty"
# Version: 0.1

echo "kitty not found, installing..."
if command -v apt &>/dev/null; then
  sudo apt update
  sudo apt install -y kitty
else
  echo "Package manager not supported"
fi
