#!/usr/bin/env bash
# Author: Alalilacias
# Description: Installs latex2text via pip3
# Syntax: source "$HOME/.dotfiles/.config/dotfiles/scripts/latex2text"
# Version: 0.4

log_debug "Checking for pip3..."
if ! command -v pip3 &>/dev/null; then
  log_error "pip3 is not installed. Cannot install latex2text."
  return 1
fi

log_debug "Installing latex2text using pip..."
pip3 install --user pylatexenc

log_info "latex2text installed."
return 0
