#!/usr/bin/env bash
# Author: Alalilacias
# Description: Installs Lazygit
# Syntax: source "$HOME/.dotfiles/.config/dotfiles/scripts/lazygit"
# Version: 0.1

echo "lazygit not found, installing..."
if command -v apt &>/dev/null; then
  LAZYGIT_VERSION=$(curl -s "https://api.github.com/repos/jesseduffield/lazygit/releases/latest" | grep -Po '"tag_name": *"v\K[^"]*')
  curl -Lo lazygit.tar.gz "https://github.com/jesseduffield/lazygit/releases/download/v${LAZYGIT_VERSION}/lazygit_${LAZYGIT_VERSION}_Linux_x86_64.tar.gz"
  tar xf lazygit.tar.gz lazygit
  sudo install lazygit -D -t /usr/local/bin/
  rm lazygit.tar.gz lazygit
else
  echo "Package manager not supported"
fi
