#!/usr/bin/env bash
# Author: Alalilacias
# Description: Installs libstdc++-12-dev
# Syntax: source "$HOME/.dotfiles/.config/dotfiles/scripts/libstdc++-12-dev"
# Version: 0.1

echo "libstdc++-12-dev not found, installing..."
if command -v apt &>/dev/null; then
  sudo apt update
  sudo apt install -y libstdc++-12-dev
else
  echo "Package manager not supported"
fi
