#!/usr/bin/env bash
# Author: Alalilacias
# Description: Installs Luarocks
# Syntax: source "$HOME/.dotfiles/.config/dotfiles/scripts/luarocks"
# Version: 0.1

echo "luarocks not found, installing..."
if command -v apt &>/dev/null; then
  
  sudo apt install -y luarocks
else
  echo "Package manager not supported"
fi
