#!/usr/bin/env bash
# Author: Alalilacias
# Description:
# Version: 0.1

echo "lynx not found, installing..."
if command -v apt &>/dev/null; then
  
  sudo apt install -y lynx
else
  echo "Package manager not supported"
fi
