#!/usr/bin/env bash
# Author: Alalilacias
# Description: Installs Neovim Python provider into .local/tools
# Syntax: source "$HOME/.dotfiles/.config/dotfiles/scripts/neovim-pip"
# Version: 0.3

if ! command -v pip3 &>/dev/null; then
  log_error "pip3 is required but not found in PATH."
  return 1
fi

pip3 install --user pynvim
