#!/usr/bin/env bash
# Author: Alalilacias
# Description: Installs Neovim npm provider into .local/tools and symlinks binary
# Syntax: source "$HOME/.dotfiles/.config/dotfiles/scripts/neovim-npm"
# Version: 0.3

npm install -g neovim

log_debug "neovim npm package installed"
