#!/usr/bin/env bash
# Author: Alalilacias
# Description: Installs Neovim Ruby gem locally into .local/tools
# Syntax: source "$HOME/.dotfiles/.config/dotfiles/scripts/neovim-gem"
# Version: 0.3

if ! command -v gem &>/dev/null; then
  log_error "RubyGems (gem) not found in PATH."
  return 1
fi

sudo gem install neovim
