#!/usr/bin/env bash
# Author: Alalilacias
# Description: Installs Node using fnm
# Syntax: source "$HOME/.dotfiles/.config/dotfiles/scripts/node"
# Version: 0.2

echo "node not found, installing..."

if ! command -v fnm &>/dev/null; then
  echo "fnm is not installed. Please install it before running this script."
  exit 1
fi

echo "Installing latest Node.js LTS via fnm..."
fnm install --lts
fnm use -- --lts
fnm default lts

echo "Node.js installation complete."
