#!/usr/bin/env bash
# Author: Alalilacias
# Description: Installs Node using fnm
# Syntax: source "$HOME/.dotfiles/.config/dotfiles/scripts/node"
# Version: 0.4

if ! command -v fnm &>/dev/null; then
  log_error "fnm is not installed. Please install it before running this script."
  return 1
fi

log_debug "Determining latest Node.js LTS version with fnm..."
LTS_VERSION=$(fnm ls-remote --lts --latest | awk '{print $1}')

if [[ -z "$LTS_VERSION" ]]; then
  log_error "Failed to detect latest LTS version of Node.js"
  return 1
fi

log_debug "Installing Node.js $LTS_VERSION..."
fnm install "$LTS_VERSION"
fnm use "$LTS_VERSION"
fnm default "$LTS_VERSION"

log_info "Node.js $LTS_VERSION installed and set as default."
return 0
