#!/usr/bin/env bash
# Author: Alalilacias
# Description: Installs Neovim
# Syntax: source "$HOME/.dotfiles/.config/dotfiles/scripts/nvim"
# Version: 0.1

echo "nvim not found, installing..."
if command -v apt &>/dev/null; then
  echo "Installing Neovim (unstable branch)..."
  if ! grep -q "neovim-ppa" /etc/apt/sources.list /etc/apt/sources.list.d/* 2>/dev/null; then
    sudo add-apt-repository -y ppa:neovim-ppa/unstable
  fi
  sudo apt-get update
  sudo apt-get install -y neovim
else
  echo "Package manager not supported"
fi
