#!/usr/bin/env bash
# Author: Alalilacias
# Description: Installs the latest Neovim following the build guide on the main repository: https://github.com/neovim/neovim/blob/master/BUILD.md
# Version: 0.4

DEPENDENCIES=(ninja-build gettext cmake curl build-essential)
IS_LOGGER_AVAILABLE=false
NEOVIM_REPO="https://github.com/neovim/neovim"
NEOVIM_DIR="${HOME}/.local/src/neovim"
NEOVIM_INSTALL_DIR="${HOME}/.local"

main() {
  logging_setup

  if command -v apt &>/dev/null; then
    debian_installation
  else
    log error "Unsupported system: no known package manager found"
    return 1
  fi
}
logging_setup() { declare -F log_info >/dev/null && IS_LOGGER_AVAILABLE=true; }
log() {
  local level="$1"
  local message="$2"

  if $IS_LOGGER_AVAILABLE; then
    case "$level" in
    debug) log_debug "$message" ;;
    info) log_info "$message" ;;
    warn) log_warn "$message" ;;
    error) log_error "$message" ;;
    *) log_debug "$message" ;;
    esac
  else
    echo message
  fi
}
debian_installation() {
  log info "Installing dependencies..."
  sudo apt-get update -qq
  sudo apt-get install -y "${DEPENDENCIES[@]}"

  log info "Cloning Neovim repository..."
  if [[ -d "$NEOVIM_DIR" ]]; then
    log debug "Neovim source already cloned, pulling latest changes..."
    git -C "$NEOVIM_DIR" pull --rebase
  else
    git clone "$NEOVIM_REPO" "$NEOVIM_DIR"
  fi

  build_and_install
}
build_and_install() {
  log info "Building Neovim..."
  cd "$NEOVIM_DIR"
  make CMAKE_BUILD_TYPE=RelWithDebInfo CMAKE_INSTALL_PREFIX="$NEOVIM_INSTALL_DIR"

  log info "Installing Neovim..."
  make install

  log info "Neovim installed to $NEOVIM_INSTALL_DIR/bin/nvim"
}

main
