#!/usr/bin/env bash
# Author: Alalilacias
# Description:
# Version: 0.1

echo "openjdk-17-jdk not found, installing..."
if command -v apt &>/dev/null; then
  
  sudo apt install -y openjdk-17-jdk
else
  echo "Package manager not supported"
fi
