#!/usr/bin/env bash
# Author: Alalilacias
# Description: Installs pandoc
# Syntax: source "$HOME/.dotfiles/.config/dotfiles/scripts/pandoc"
# Version: 0.1

echo "pandoc not found, installing..."
if command -v apt &>/dev/null; then
  sudo apt update
  sudo apt install -y pandoc
else
  echo "Package manager not supported"
fi
