#!/usr/bin/env bash
# Author: Alalilacias
# Description: Installs php
# Syntax: source "$HOME/.dotfiles/.config/dotfiles/scripts/php"
# Version: 0.1

echo "php not found, installing..."
if command -v apt &>/dev/null; then
  sudo apt update
  sudo apt install -y php
else
  echo "Package manager not supported"
fi
