#!/usr/bin/env bash
# Author: Alalilacias
# Description: Installs pip3 for Python 3
# Syntax: source "$HOME/.dotfiles/.config/dotfiles/scripts/python3-pip"
# Version: 0.1

echo "pip3 not found, installing..."
if command -v apt &>/dev/null; then
  sudo apt update
  sudo apt install -y python3-pip
else
  echo "Package manager not supported"
fi
