#!/usr/bin/env bash
# Author: Alalilacias
# Description: Installs Ripgrep
# Syntax: source "$HOME/.dotfiles/.config/dotfiles/scripts/ripgrep"
# Version: 0.1

echo "ripgrep not found, installing..."
if command -v apt &>/dev/null; then

  sudo apt install -y ripgrep
else
  echo "Package manager not supported"
fi
