#!/usr/bin/env bash
# Author: Alalilacias
# Description: Installs Ruby development headers
# Syntax: source "$HOME/.dotfiles/.config/dotfiles/scripts/ruby-dev"
# Version: 0.1

echo "ruby-dev not found, installing..."
if command -v apt &>/dev/null; then
  sudo apt update
  sudo apt install -y ruby-dev
else
  echo "Package manager not supported"
fi
