#!/usr/bin/env bash
# Author: Alalilacias
# Description: Installs Software-properties-common
# Syntax: source "$HOME/.dotfiles/.config/dotfiles/scripts/software-properties-common"
# Version: 0.1

echo "software-properties-common not found, installing..."
if command -v apt &>/dev/null; then
  
  sudo apt install -y software-properties-common
else
  echo "Package manager not supported"
fi
