#!/usr/bin/env bash
# Author: Alalilacias
# Description: Installs sqlite3
# Syntax: source "$HOME/.dotfiles/.config/dotfiles/scripts/sqlite3"
# Version: 0.1

echo "sqlite3 not found, installing..."
if command -v apt &>/dev/null; then
  sudo apt update
  sudo apt install -y sqlite3
else
  echo "Package manager not supported"
fi
