#!/usr/bin/env bash
# Author: Alalilacias
# Description: Installs texlive-xetex
# Syntax: source "$HOME/.dotfiles/.config/dotfiles/scripts/texlive-xetex"
# Version: 0.1

echo "texlive-xetex not found, installing..."
if command -v apt &>/dev/null; then
  sudo apt update
  sudo apt install -y texlive-xetex
else
  echo "Package manager not supported"
fi
