#!/usr/bin/env bash
# Author: Alalilacias
# Description: Installs tree
# Syntax: source "$HOME/.dotfiles/.config/dotfiles/scripts/tree"
# Version: 0.1

echo "tree not found, installing..."
if command -v apt &>/dev/null; then
  sudo apt update
  sudo apt install -y tree
else
  echo "Package manager not supported"
fi
