#!/usr/bin/env bash
# Author: Alalilacias
# Description: Installs Zsh
# Syntax: source "$HOME/.dotfiles/.config/dotfiles/scripts/zsh"
# Version: 0.1

echo "zsh not found, installing..."
if command -v apt &>/dev/null; then
  sudo apt update
  sudo apt install -y zsh
else
  echo "Package manager not supported"
fi

